config/routes.rb
Rails.application.routes.draw do
  resources :lessons
  devise_for :users
  resources :courses, only: [:new, :index, :show, :edit, :create]
  resources :users, only: [:index, :edit, :show, :update]
  root "home#index"

  get 'home/activity'
  get 'static_pages/privacy_policy'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  validates :title, :content, :course, presence: true

  extend FriendlyId
  friendly_id :title, use: :slugged

  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user }

  def to_s
    title
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy ]

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1 or /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:title, :content, :course_id)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@lesson) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :content
    -#= f.association :course
    = f.input :course_id, input_html: {value: @lesson.course_id || params[:course_id]}, as: :hidden

  .form-actions
    = f.button :submit

app/views/lessons/_lesson.html.haml
.card
  .card-header
    = link_to lesson.title, lesson
  .card-body
    = lesson.content
    = lesson.course
  .card-footer
    = link_to 'Edit', edit_lesson_path(lesson), class: 'btn btn-sm btn-warning'
    = link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

app/views/lessons/edit.html.haml
%h1 Editing lesson

= render 'form'

= link_to 'Show', @lesson
\|
= link_to 'Back', lessons_path

app/views/lessons/index.html.haml
%h1 Listing lessons

%table
  %thead
    %tr
      %th Title
      %th Content
      %th Course
      %th
      %th
      %th

  %tbody
    - @lessons.each do |lesson|
      %tr
        %td= lesson.title
        %td= lesson.content
        %td= lesson.course
        %td= link_to 'Show', lesson
        %td= link_to 'Edit', edit_lesson_path(lesson)
        %td= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Lesson', new_lesson_path

app/views/lessons/new.html.haml
%h1 New lesson

= render 'form'

= link_to 'Back', lessons_path

app/views/lessons/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @lesson.title
%p
  %b Content:
  = @lesson.content
%p
  %b Course:
  = @lesson.course

= link_to 'Edit', edit_lesson_path(@lesson)
\|
= link_to 'Back', lessons_path