config/routes.rb
Rails.application.routes.draw do
  resources :lessons
  devise_for :users
  resources :courses, only: [:new, :index, :show, :edit, :create]
  resources :users, only: [:index, :edit, :show, :update]
  root "home#index"

  get 'home/activity'
  get 'static_pages/privacy_policy'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @course_all = Course.all
    @ransack_courses = Course.ransack(params[:courses_search], search_key: :courser_search)
    @courses = @ransack_courses.result.includes(:user)
    @latest_courses = Course.all.limit(2).order(created_at: :desc)
  end

  # GET /courses/1 or /courses/1.json
  def show
    @lessons = @course.lessons
  end

  # GET /courses/new
  def new
    @course = Course.new
    authorize @course
  end

  # GET /courses/1/edit
  def edit
    authorize @course
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    @course.user = current_user
    authorize @course

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
    authorize @course
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
    authorize @course
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description, :short_description, :level, :price, :language)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.haml
.card 
  .card-container 
    .fa.fa-graduation-cap
    = link_to course.title, course
  .card-body 
    = course.description
  .card-footer
    .fa.fa-globe-africa
    = course.language
    = course.level
    = course.price
    = course.created_at
    = course.lessons.count
    = number_to_currency(course.price)
    .row
      .fa.fa-chalkboard-teacher
      = course.user.username
  - if policy(course).edit?
    .card-footer
      /- if policy(course).edit?
      = link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning'
      /- if policy(course).destroy?
      = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

app/views/courses/_form.html.haml
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.label :description
    = f.rich_text_area :description
    = f.input :short_description
    = f.input :language, collection: Course.languages, include_blank: true
    = f.input :level, collection: Course.levels, include_blank: true
    = f.input :price
    
  .form-actions
    = f.button :submit
 

app/views/courses/edit.html.haml
%h1 Editing course

= render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
%h1 Все курсы

.card-columns
.row
  .col-md-2
    = search_form_for @ransack_courses, as: :courses_search, url: @ransack_path do |f|
      = f.label 'Название'
      = f.search_field :title_cont, placeholder: 'Название', class: 'form-control form-control-sm'
      = f.label :description
      = f.search_field :short_description_cont, placeholder: 'Описание', class: 'form-control form-control-sm'
      /= f.search_field :language_cont, placeholder: 'Language', class: 'form-control form-control-sm'
      /= f.select :language_cont, ['English', 'Polish', 'Russian'], include_blank: true, class: 'form-control form-control-sm'
      = f.label :language
      = f.select :language_cont, Course.languages, include_blank: true
      /= f.search_field :level_cont, placeholder: 'Level', class: 'form-control form-control-sm'
      = f.label :level
      = f.select :level_cont, Course.levels, include_blank: true
      = f.label :price
      = f.search_field :price_eq, placeholder: 'Цена', class: 'form-control form-control-sm'
      = f.label :teacher
      = f.search_field :user_email_cont, placeholder: 'Email', class: 'form-control form-control-sm'
      = f.submit
    = link_to 'перезагрузить', courses_path


  .col-md-10
    .card-columns
      - @courses.each do |course|
        = render partial: 'course', collection: @courses

app/views/courses/new.html.haml
%h1 New course

= render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.haml
= render 'courses/course', course: @course

%p#notice= notice

%p
  %b Название:
  = @course.title
%p
  %b Описание:
  = @course.description
.col-lg-6
  = link_to 'Add lesson', new_lesson_path(course_id: @course.id)
  - @lessons.each do |lesson|
    = render 'lessons/lesson', lesson: lesson

= link_to 'Редактировать', edit_course_path(@course)
\|
= link_to 'Назад', courses_path