config/routes.rb
Rails.application.routes.draw do
  resources :lessons
  devise_for :users
  resources :courses, only: [:new, :index, :show, :edit, :create]
  resources :users, only: [:index, :edit, :show, :update]
  root "home#index"

  get 'home/activity'
  get 'static_pages/privacy_policy'
end

app/views/layouts/_footer.html.haml
%hr

%footer
  .container
    .row
      .col-md-4
        Copyright
        © 
        = Time.now.year
        CourseApp
        .row
        .fa.fa-envelope
        = mail_to 'yegor.rb@gmail.com'
        .row
      .col-md-4 
        Политика конфиденциальности
        .row
        Правила
      .col-md-4
        О нас
        .row
        = link_to 'Создать курс на CourseApp', new_course_path
.p-2

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.navbar-brand{href: root_path} CourseApp
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user 
      %ul.navbar-nav.mr-auto
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home
            Домой
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(courses_path)}"}
          = link_to courses_path, class: 'nav-link' do
            .fa.fa-graduation-cap
            Курсы
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_course_path)}"}
          = link_to new_course_path, class: 'nav-link' do
            .fa.fa-book-reader
            Создать курс
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(users_path)}"}
          = link_to users_path, class: 'nav-link' do
            .fa.fa-book-reader
            Пользователи
        - if @ransack_courses.present?
          = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
            .input-group
              = f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off
              %span.input-group-append
                %button.btn.btn-primary.btn-sm{:type => "submit"}
                  %span.fa.fa-search{"aria-hidden" => "true"}            
        .form-inline.my-2.my-lg-0
          = form_tag(courses_path, method: :get) do 
            .input-group
              = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
              %span.input-group-append
                %button.btn.btn-primary.btn-sm{:type => "submit"}
                  %span.fa.fa-search{"aria-hidden" => "true"}                  
      %ul.navbar-nav.mr-right
        %li.nav-item{class: "#{'active font-weight-bold'}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-bell
            Активность
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            %b= current_user.username
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
            = link_to edit_user_registration_path, class: "dropdown-item" do
              .fa.fa-cog
              %b Настройки профиля
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              .fa.fa-sign-out-alt
              %b Выйти
    - else
      %ul.navbar-nav.ml-auto
        %li.nav-item= link_to 'Регистрация', new_user_registration_path, class: 'nav-link'
        %li.nav-item= link_to 'Войти', new_user_session_path, class: 'nav-link'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", role: 'alert'}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Coursehub
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
  = render 'layouts/header'
  .container
    = render 'layouts/messages'
    = yield
  .bg-dark
    = render 'layouts/footer'